spark_locals_without_parens = [
  access: 1,
  allow_embed?: 1,
  autoplay?: 1,
  caption: 1,
  category: 1,
  content_loc: 1,
  description: 1,
  duration: 1,
  expiration_date: 1,
  family_friendly?: 1,
  gallery_loc: 1,
  gallery_title: 1,
  genres: 1,
  geo_location: 1,
  image: 0,
  image: 1,
  keywords: 1,
  license: 1,
  live?: 1,
  loc: 1,
  news: 0,
  news: 1,
  platform_list: 1,
  platform_relationship?: 1,
  player_loc: 1,
  price: 1,
  price_currency: 1,
  price_resolution: 1,
  price_type: 1,
  priority: 1,
  publication_date: 1,
  publication_language: 1,
  publication_name: 1,
  rating: 1,
  read_action: 1,
  relationship?: 1,
  requires_subscription?: 1,
  restriction: 1,
  show_episode_number: 1,
  show_episode_title: 1,
  show_premier_date: 1,
  show_season_number: 1,
  show_title: 1,
  show_video_type: 1,
  sitemap: 1,
  sitemap: 2,
  stock_tickers: 1,
  thumbnail_loc: 1,
  title: 1,
  uploader: 1,
  uploader_info: 1,
  url: 1,
  video: 0,
  video: 1,
  view_count: 1
]

[
  import_deps: [:ash],
  plugins: [Spark.Formatter],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 80,
  trailing_comma: true,
  local_pipe_with_parens: true,
  single_clause_on_do: true,
  locals_without_parens: spark_locals_without_parens,
  export: [locals_without_parens: spark_locals_without_parens]
]
