defmodule Example.Repo.Migrations.AddArticleResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:articles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :author, :text
      add :content, :text
      add :description, :text
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:articles)
  end
end